manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: golioth
      url-base: https://github.com/golioth
    - name: gardin
      url-base: git@github.com:gardinltd

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis
          - hal_espressif
          - mbedtls
          - lvgl
          - mcuboot

    - name: golioth
      repo-path: golioth-firmware-sdk
      remote: golioth
      path: modules/lib/golioth-firmware-sdk
      revision: main
      submodules: true

    - name: ros2
      repo-path: libros2-zephyr
      remote: gardin
      revision: main
      path: modules/ros2