name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: rasprover

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: rasprover
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: rasprover
        shell: bash
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Twister Tests
        working-directory: rasprover
        shell: bash
        run: |
          west twister -T tests -v --inline-logs --integration